dist: xenial   # required for Python >= 3.7

sudo: false

language: python

services:
  - mongodb

cache: pip

python:
  - "3.4"
  - "3.5"
  - "3.6"
#  - "3.7"
  - "3.7-dev"  # 3.7 development branch
#  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
  - "pypy3.5"  # Pypy3 3.5.3

before_script:
  - sleep 15
  - mongo vakt_db --eval 'db.createUser({user:"test_user",pwd:"test_password",roles:["readWrite"]});'

install:
  - make deps

script:
  - make coverage
  - make bench

after_success:
  - bash <(curl -s https://codecov.io/bash)
